### ISSUE TITLE
consider naming the format shower_presentation

### ISSUE THREAD

**Issue by jjallaire** [MangoTheCat/rmdshower#21]
Within the RStudio Preview we have some special behavior that is triggered if we know a format is a Presentation:
1. We automatically restore the HTML Preview to the last viewed anchor tag (i.e. last viewed slide); 
2. We provide a slightly wider preview window (relative to the hight)

Note that in the current release of RStudio we always do #1 (restore the anchor) however in the upcoming release we'll be looking for the _presentation suffix to trigger this, see: https://github.com/rstudio/rstudio/blob/f2860cf04082e54561102803e46e92aac9276152/src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdRenderResult.java#L98-L102

If you have strong reasons for keeping the name `shower` then we can certainly hard-code that format to also restore the last viewed slide. Let me know what you think.

**Comment by gaborcsardi** [comment]
Thanks. I don't have strong feelings, we can certainly change it to `shower_presentation`.

I'll wait another week, in case other bugs come up, which is not unlikely, and submit a fixed release next week.
