### ISSUE TITLE
problem rendering skeleton.Rmd example

### ISSUE THREAD

**Issue by luca-scr** [MangoTheCat/rmdshower#28]
Hi, 
I was giving a try to rmdshower which looks very promising, but I was not able to reproduce the default skeleton example.
A screenshot of the output html that I obtain is attached below.
Many thanks for any help.

Luca

``` r
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  utils     datasets  grDevices methods   base     

other attached packages:
[1] RColorBrewer_1.1-2

loaded via a namespace (and not attached):
 [1] magrittr_1.5       rsconnect_0.4.3    htmltools_0.3.5    tools_3.3.1        yaml_2.1.13        Rcpp_0.12.6       
 [7] stringi_1.1.1      rmarkdown_1.0.9002 rmdshower_2.0.0    stringr_1.1.0      digest_0.6.9       evaluate_0.9
```

![shower_html](https://cloud.githubusercontent.com/assets/11585946/17999538/f6a49b56-6b79-11e6-90cf-43209590ebac.png)

**Comment by gaborcsardi** [comment]
Please provide a reproducible example, i.e. your Rmd file, and also the commands you ran.

**Comment by luca-scr** [comment]
Thanks for your quick reply. The Rmd file (zipped) is attached below. 
Usually I run knitr from the button on RStudio, but the following command give the same output:

``` r
rmarkdown::render("~/Desktop/shower_slides.Rmd")
```

[shower_slides.Rmd.zip](https://github.com/MangoTheCat/rmdshower/files/438895/shower_slides.Rmd.zip)

**Comment by gaborcsardi** [comment]
Looks like your Rmd is for the previous version of shower, we changed the markup a bit to make it similar to other templates. E.g. Slide headings are created by `##` and not `#` now. Please use the most recent skeleton as a template, from here:

https://github.com/MangoTheCat/rmdshower/blob/master/inst/examples/skeleton.Rmd
https://raw.githubusercontent.com/MangoTheCat/rmdshower/master/inst/examples/skeleton.Rmd

**Comment by luca-scr** [comment]
Yes it works now. It looks like the files 

./examples/skeleton.Rmd
./rmarkdown/templates/shower/skeleton/skeleton.Rmd

are different, and the second is the one giving me the problems. 
In fact, I started using the template from File -> New File -> R Markdown menu in RStudio.
Maybe you may want to update this template file too. 

Thanks for you support.

Luca

**Comment by gaborcsardi** [comment]
Oh, I see. I think that template file is not actually needed, but I'll take a look. Please leave this issue open, so I don't forget it.

**Comment by cboettig** [comment]
@gaborcsardi Looks like this issue still impacts the template provided by the File -> New File -> R Markdown menu in RStudio.

**Comment by dougmet** [comment]
I think it's because `inst/examples/skeleton.Rmd` was updated but this is not the one that RStudio looks for when you create a new file. It's `inst/rmarkdown/templates/shower/skeleton/skeleton.Rmd` and this had not been updated. Submitting PR to fix it.

**Comment by dougmet** [comment]
Just realised you already new that. The second file `inst/rmarkdown/templates/shower/skeleton/skeleton.Rmd` is the one that RStudio loads when you select File -> New File -> R  as @cboettig says
