### ISSUE TITLE
Cannot Install for Missing rprojroot Package

### ISSUE THREAD

**Issue by ArthurZ** [MangoTheCat/rmdshower#32]
Since the installation fails if `rprojroot` package is not present I suggest adding it into the dependencies to install.
Log:
`Installing rmdshower
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/me/AppData/Local/Temp/RtmpsnEWXI/devtools28c043cf7d31/MangoTheCat-rmdshower-cbe203c"  \
  --library="C:/Program Files/R/R-3.3.2/library" --install-tests `

* installing *source* package 'rmdshower' ...
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'rprojroot'
ERROR: lazy loading failed for package 'rmdshower'
* removing 'C:/Program Files/R/R-3.3.2/library/rmdshower'
Error: Command failed (1)

**Comment by gaborcsardi** [comment]
`rmdshower` does not depend on `rprojroot`. It is probably a bug in your installer. Here is an alternative:
```r
source("https://install-github.me/MangoTheCat/rmdshower")
```

**Comment by ArthurZ** [comment]
But installing `rprojroot` indeed did made installing `rmdshower` possible.

**Comment by gaborcsardi** [comment]
Still, it is a bug in the installer. The installer should pick up the dependency (which is not from `rmdshower`) and install `rprojroot` automatically.

By installing it manually you worked around the installer bug.

**Comment by gaborcsardi** [comment]
It is a `devtools` bug: https://github.com/hadley/devtools/issues/1409
