### ISSUE TITLE
shared directory for multiple presentations?

### ISSUE THREAD

**Issue by beanumber** [MangoTheCat/rmdshower#39]
Thanks for the work on this!

Is there a way to have the directory of includes shared over multiple presentations? Suppose I have presentations `a.Rmd, b.Rmd, c.Rmd, ...`. With the `self_contained` option set to `false` (it never works for me when set to `true`), this creates directories `a_files, b_files, c_files, ...` I suspect that all these directories are the same. Is there a way to just have one of them?

**Comment by gaborcsardi** [comment]
I don't know of a way. I think this is a generic `rmarkdown` question, so you might try asking it there.

**Comment by beanumber** [comment]
OK, thanks!
